### ISSUE TITLE
parametrize to allow usage of external minio end influxdb

### ISSUE THREAD

**Issue by gioppoluca** [ddosify/ddosify-helm-charts#2]
there is no option to allow usage of external minio or influxdb.
please add in chart this capability

**Comment by fatihbaltaci** [comment]
Hello @gioppoluca, Thank you for raising this issue. 

We will add this option to our helm chart. In addition, we're also considering replacing Minio with SeaweedFS. Once they are ready, we will inform you through this thread.

And could you please share your use cases for the external usage of influxdb so that we can better understand your needs?

**Comment by fatihbaltaci** [comment]
Hi @gioppoluca, Ddosify chart `1.3.0` is ready on GitHub. You can upgrade Ddosify using [these](https://github.com/ddosify/ddosify-helm-charts#upgrading-the-ddosify-chart) instructions.

You can set your external databases (postgres and influxdb) now. Here are the instructions: https://github.com/ddosify/ddosify-helm-charts#external-database-optional

If you have any questions, please let me know.

**Comment by gioppoluca** [comment]
tested and it works
